- name: Validate the sudoers file before saving
  become: true
  lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%simon ALL='
      line: '%simon ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'

- name: Ensure we have eth0
  become: true
  ansible.builtin.file:
    dest:  /etc/systemd/network/99-default.link
    src: /dev/null
    state: link
    force: yes